# Generated by Django 6.0.1 on 2026-01-18 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_jobseekerapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
