# Generated by Django 6.0.1 on 2026-01-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_category_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#FF0000', help_text='color name or Hex color code, e.g. #FF0000 or red', max_length=7),
        ),
    ]
